#!/bin/sh
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push testeditor/angular-sut:snapshot
if [[ $TRAVIS_TAG = v* ]]; then
  docker tag testeditor/angular-sut:snapshot testeditor/web:$TRAVIS_TAG
  docker push testeditor/angular-sut:$TRAVIS_TAG
  docker tag testeditor/angular-sut:snapshot testeditor/web:latest
  docker push testeditor/angular-sut:latest
fi
